# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kwangmin Park
title: Professor at Sejong University
email: kmpark@sejong.ac.kr
website: www.github.com/KwangminPark

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: who4u78
github_username:  KwangminPark
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sapientia.a.dei
linkedin_username: kwangminpark
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: who4u78
# googleplus_username: +jekyll
orcid_username: 0000-0002-2749-8932

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kwangmin and I'm a Professor at Sejong University in Seoul, Korea. I'm affiliated in the Dpt. of Foodservice MGMT. I'm interested in the Business analytics with big data and my research focus is the strategic management in the restaurant industry.

  I am very excited to interact with you!!

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sejong University
        link: sejong.ac.kr
        link_text: Sejong Univ.
        sub_title: Professor
        caption: March 2011 - Present
        quote: >
          Inventing the future of restaurants via Data!!
        description: | # this will include new lines to allow paragraphs
            »	Teaching Undergrad courses: Strategic MGMT; Business Analytics; MGMT Science; Operations MGMT

            »	Teaching Grad courses: Research Methodology and others
      - layout: left
        title: E-Mart in Shinsegae Group
        link: store.emart.com
        link_text: E-Mart Web
        sub_title: Controller & Food Procurer
        caption: January 2003 - August 2005
        quote: >
          HMR (Home Meal Replacement) is the RTE (Ready-to-eat) only before my touch
        description: | # this will include new lines to allow paragraphs
            »	Controlling the food matiarials from order to distribution

            »	Managing the price and cost structure

            »	Analyzing retail data

            »	Negotiating with supplers

            »	Developting new products

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Purdue University, West Lafayette, IN
        caption: August 2007 - August 2010
        sub_title: Ph.D. Hospitality & Tourism MGMT
        quote: >
          Top-ranked programs in hospitality and tourism management all over the world
        description: | # this will include new lines to allow paragraphs
          »	Dissertation: Corporate Diversification Strategy and Firm Performance in the U.S. Restaurant Industry

          »	Major Advisor: Dr. SooCheong (Shawn) Jang
      - layout: left
        title: Purdue University, West Lafayette, IN
        caption: August 2005 - August 2007
        sub_title: MS Hospitality & Tourism MGMT
        quote: >
          Top-ranked programs in hospitality and tourism management all over the world
        description: | # this will include new lines to allow paragraphs
          »	Thesis: Financial Leverage and Firm Investment in U.S. Restaurant Firms

          »	Major Advisor: Dr. SooCheong (Shawn) Jang
      - layout: left
        title: Yonsei University, Seoul, Korea
        caption: March 1996 - February 2003
        sub_title: BS Food & Nutrition / Interior Architecture & Built Environment (Double Major) and Business (Minor)
        quote: >
          Pursuing interdisciplinary convergence!!
        description: | # this will include new lines to allow paragraphs
          »	Scholarship from	the Un-bong Foundation, Seoul, Korea, 2002

          »	High Honor Student from Yonsei University, Seoul, Korea, 2002

          »	Honor Student from Yonsei University, Seoul, Korea, 2001

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
     Refereed Journal (Accepted & In Press)
     - Park, K., & Jang, S. (2022) Do coffee chains have strategic superiority? An examination of the intra-regional and size strategies of coffee chains. International Journal of Hospitality Management, 105, August, 103254. [Link](https://www.sciencedirect.com/science/article/pii/S0278431922001165?casa_token=2WAwm4Aq3foAAAAA:3MnjjsoaIFGPzkSQnoNspf-X_jqIRRoMX7zp8a3A-PwPdu8R7PbSP3ZgIZWqmANhNAp7VRhLDQ)
     - Park, K., & Kong, k. (2022) Certification Paradox: Reverse Response on the Non-Hygiene Restaurant Certification.  Journal of Hospitality and Tourism Management, 51, 268-278. [Link](https://www.sciencedirect.com/science/article/abs/pii/S1447677022000651?casa_token=d8aercKEsdIAAAAA:NVmaMjTyAUjrTfV1-aGY_PB8Ipvnwx6X5N5krqdELYYs1SYSK-Zh5uN7IoUbxDtF_JGdLaSUEg)
     - Park, K., & Jang, S. (2021) A study of value-relevance and reliability of intangible assets: What do we know from the restaurant industry? Journal of Hospitality and Tourism Management, 47, 104-113. [Link](https://www.sciencedirect.com/science/article/pii/S1447677021000334?casa_token=Y50c1raf73wAAAAA:PJZg3Oy9Yj0dV36ENvCQKcLXN5NUrdG3mlJJIMh1eSiJqJeAob123atMIt4rVEfFd8e-yW6Fug)
     - Park, K. (2019) The Effect of Certification Belief and Substitute on Customer Trust between Low and High Brand Equity Restaurants. Food Service Industry Journal, 15, 3, 141-149. [Link](https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE09220964)
     - Park, K., & Jang, S. (2019) Cash Regimes and the Franchise system: An Extension of the Marginal Value of Cash. Tourism Economics, 25, 2 (March), 235-252. [Link](https://journals.sagepub.com/doi/10.1177/1354816618797865)
     - Jang, S. & Park, K. (2019) A sustainable franchisor-franchisee relationship model: Toward the franchise win-win theory. International Journal of Hospitality Management, 76, Part B (January), 13-24. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0278431918305024)
     - Park, K., & Jang, S. (2018) Is franchising an additional financing source for franchisors? A Blinder–Oaxaca decomposition analysis. Tourism Economics, 24, 5 (August), 541-559. [Link](https://journals.sagepub.com/doi/10.1177/1354816618757561)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
